---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quay-s3-setup
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # Layer 1: Create ServiceAccount/RBAC
  labels:
    app: quay-s3-setup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-s3-setup
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # Layer 1: Create ServiceAccount/RBAC
rules:
# Read template secret and create new secret with real credentials in quay namespace
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch", "update"]
  resourceNames: ["quay-init-config-bundle-secret", "quay-config-with-s3"]
# Need to create quay-config-with-s3 secret without resourceName restriction
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-s3-setup-quay-resources
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # Layer 1: Create ServiceAccount/RBAC
rules:
# ObjectBucketClaim access - OBC is in quay namespace
- apiGroups: ["objectbucket.io"]
  resources: ["objectbucketclaims"]
  verbs: ["get", "list", "watch"]
# Secrets access for S3 credentials in quay namespace
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# ConfigMaps access for S3 endpoint info in quay namespace
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quay-s3-setup
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # Layer 1: Create ServiceAccount/RBAC
subjects:
- kind: ServiceAccount
  name: quay-s3-setup
  namespace: {{ .Values.quay.namespace }}
roleRef:
  kind: Role
  name: quay-s3-setup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quay-s3-setup-quay-resources
  namespace: {{ .Values.quay.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"  # Layer 1: Create ServiceAccount/RBAC
subjects:
- kind: ServiceAccount
  name: quay-s3-setup
  namespace: {{ .Values.quay.namespace }}
roleRef:
  kind: Role
  name: quay-s3-setup-quay-resources
  apiGroup: rbac.authorization.k8s.io
