---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.noobaa.namespace }}
  labels:
    openshift.io/cluster-monitoring: "true"
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Layer 1: Create namespace first
