{{- if .Values.keycloak.defaultConfig }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: keycloak-users
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: keycloak-users
    template:
      type: Opaque
      data:
        qtodo-admin-password: "{{ `{{ .qtodo_admin_password }}` }}"
        qtodo-user1-password: "{{ `{{ .qtodo_user1_password }}` }}"
        rhtas-user-password: "{{ `{{ .rhtas_user_password }}` }}"
  data:
  - secretKey: qtodo_admin_password
    remoteRef:
      key: secret/data/global/keycloak-users
      property: qtodo-admin-password
  - secretKey: qtodo_user1_password
    remoteRef:
      key: secret/data/global/keycloak-users
      property: qtodo-user1-password
  - secretKey: rhtas_user_password
    remoteRef:
      key: secret/data/global/keycloak-users
      property: rhtas-user-password
{{- end }}
