{{- if .Values.keycloak.defaultConfig }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: oidc-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: oidc-client-secret
    template:
      type: Opaque
      data:
        client-secret: "{{ `{{ .client_secret }}` }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: secret/data/global/oidc-client-secret
      property: client-secret
{{- end }}
