{{- $clusters := .Values.acmManagedClusters.clusters | default list }}
{{- range $clusters }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: kubeconfig-{{ .name }}
  namespace: {{ .name }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.global.secretStore.name }}
    kind: {{ $.Values.global.secretStore.kind }}
  target:
    name: auto-import-secret
    template:
      type: Opaque
      data:
        autoImportRetry: "5"
        kubeconfig: "{{ `{{ .kubeconfig }}` }}"
  data:
  - secretKey: kubeconfig
    remoteRef:
      key: {{ .kubeconfigVaultPath }}
      property: content
{{- end }}
