global:
  localClusterDomain: apps.example.com
  secretStore:
    name: "vault-backend"
    kind: "ClusterSecretStore"

keycloak:
  name: keycloak

  ingress:
    enabled: true
    service: keycloak-service-trusted
    termination: reencrypt
    hostname: ""

  tls:
    serviceServing: true
    secret: keycloak-tls

  postgresqlDb:
    secretName: postgresql-db
    username: keycloak
    database: keycloak
    passwordVaultKey: secret/data/global/keycloak

  # Toggle to enable/disable default realm configuration
  defaultConfig: true
  # Default realm configuration
  defaultRealm:
    realm: "ztvp"
    displayName: "ZTVP Realm"
    enabled: true
    registrationAllowed: false
    clients:
      - clientId: "quarkus-app"
        name: "quarkus"
        publicClient: true
        redirectUris:
          - "*"
        webOrigins:
          - "+"
        enabled: true
        protocol: "openid-connect"
    users:
      - username: "quarkus-admin"
        createdTimestamp: 1
        enabled: true
        email: "quarkus-admin@example.com"
        emailVerified: true
        firstName: "Quarkus"
        lastName: "Admin"
        credentials:
          - type: "password"
            value: "rDlobaGjL2"
            temporary: true
        realmRoles:
          - "quarkus-admin"
        requiredActions:
          - "UPDATE_PASSWORD"
      - username: "quarkus-user1"
        createdTimestamp: 1
        enabled: true
        email: "quarkus-user1@example.com"
        emailVerified: true
        firstName: "Quarkus"
        lastName: "User-1"
        credentials:
          - type: "password"
            value: "LuOSkWDb0P"
            temporary: true
        realmRoles:
          - "viewer"
        requiredActions:
          - "UPDATE_PASSWORD"
    roles:
      realm:
        - name: "quarkus-admin"
          description: "Quarkus App Administrator"
        - name: "viewer"
          description: "Read-only access"
  # -- Keycloak realms to import
  realms: []
