global:
  localClusterDomain: apps.example.com
  secretStore:
    name: "vault-backend"
    kind: "ClusterSecretStore"

keycloak:
  name: keycloak

  ingress:
    enabled: true
    service: keycloak-service-trusted
    termination: reencrypt
    hostname: ""

  tls:
    serviceServing: true
    secret: keycloak-tls

  postgresqlDb:
    secretName: postgresql-db
    username: keycloak
    database: keycloak
    passwordVaultKey: secret/data/global/keycloak

  users:
    secretName: keycloak-users
    passwordVaultKey: secret/data/global/keycloak-users

  # Toggle to enable/disable default realm configuration
  defaultConfig: true
  # Default realm configuration
  defaultRealm:
    realm: "ztvp"
    displayName: "ZTVP Realm"
    enabled: true
    registrationAllowed: false
    clients:
      - clientId: "qtodo-app"
        name: "qtodo"
        publicClient: false
        standardFlowEnabled: true
        secret: "${QTODO_CLIENT_SECRET}"
        redirectUris:
          - "*"
        webOrigins:
          - "+"
        enabled: true
        protocol: "openid-connect"
    users:
      - username: "qtodo-admin"
        createdTimestamp: 1
        enabled: true
        email: "qtodo-admin@example.com"
        emailVerified: true
        firstName: "QTodo"
        lastName: "Admin"
        credentials:
          - type: "password"
            value: "${QTODO_ADMIN_PASSWORD}"
            temporary: true
        realmRoles:
          - "qtodo-admin"
        requiredActions:
          - "UPDATE_PASSWORD"
      - username: "qtodo-user1"
        createdTimestamp: 1
        enabled: true
        email: "qtodo-user1@example.com"
        emailVerified: true
        firstName: "QTodo"
        lastName: "User-1"
        credentials:
          - type: "password"
            value: "${QTODO_USER1_PASSWORD}"
            temporary: true
        realmRoles:
          - "viewer"
        requiredActions:
          - "UPDATE_PASSWORD"
    roles:
      realm:
        - name: "qtodo-admin"
          description: "QTodo App Administrator"
        - name: "viewer"
          description: "Read-only access"
  # -- Keycloak realms to import
  realms: []
