quay:
  namespace: quay-enterprise
  component:
    - name: clair
      managed: true
    - name: horizontalpodautoscaler
      managed: true
    - name: mirror
      managed: true
    - name: monitoring
      managed: true
    - name: postgres
      managed: true
    - name: redis
      managed: true
    - name: objectstorage
      managed: false
    - name: route
      managed: true
    - name: tls
      managed: true
    - name: quay
      managed: true
    - name: clairpostgres
      managed: true
  configBundleSecret:
    deploy: true
    name: quay-init-config-bundle-secret
  setup:
    admin:
      name: quayadmin
      email: quayadmin@example.com
    user:
      name: developer1
      email: developer1@myorg.com

job:
  image: registry.redhat.io/openshift4/ose-cli:latest

quay_config:
  org:
    name: devel
    email: devel@myorg.com
  repo: example

# Object Storage configuration - using NooBaa MCG
objectStorage:
  objectBucketClaim:
    name: quay-bucket
    bucketName: quay-datastore
    storageClass: openshift-storage.noobaa.io
