apiVersion: v2
description: Deploys resources for cluster hardening
keywords:
  - pattern
  - compliance
  - zero trust
  - hardening
name: compliance-scanning
type: application
icon: https://validatedpatterns.io/images/validated-patterns.png
version: 0.0.1
