apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: qtodo
  name: qtodo
  namespace: qtodo
{{- if or .Values.app.images.main.registry.auth .Values.global.registry.enabled }}
imagePullSecrets:
  - name: {{ .Values.app.images.main.registry.secretName }}
{{- end }}