apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qtodo-db-network-policy
  namespace: qtodo
spec:
  podSelector:
    matchLabels:
      app: qtodo-db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # PostgreSQL access restricted to qtodo app pods only
  - ports:
    - protocol: TCP
      port: 5432
    from:
    - podSelector:
        matchLabels:
          app: qtodo
  egress:
  # DNS resolution only
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
    to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-dns
