{{- if .Values.app.oidcSecret.enabled }}
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.app.oidcSecret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.app.oidcSecret.name }}
    template:
      type: Opaque
      data:
        client-secret: "{{ `{{ .client_secret }}` }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: {{ .Values.app.oidcSecret.vaultPath }}
      property: client-secret
{{- end }}
