apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    # Make the pvc before the db service
    argocd.argoproj.io/sync-wave: '5'
  labels:
    app: qtodo-db
  name: qtodo-db-pvc
  namespace: qtodo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

