apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: qtodo-db-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.postgresql.auth.secretName }}
    template:
      type: Opaque
      data:
        username: {{ .Values.postgresql.auth.username }}
        database: {{ .Values.postgresql.auth.database }}
        password: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.postgresql.auth.passwordVaultKey }}
      property: db-password