apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  labels:
    app: qtodo-db
  name: qtodo-db
  namespace: qtodo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qtodo-db
  template:
    metadata:
      labels:
        app: qtodo-db
    spec:
      containers:
      - name: postgres
        image: registry.redhat.io/rhel8/postgresql-16
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRESQL_DATABASE
          value: tasks
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              name: qtodo-db-secret
              key: username
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qtodo-db-secret
              key: password
        ports:
        - containerPort: 5432
          protocol: TCP
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: qtodo-pvc

