# Default values for qtodo
global:
  secretStore:
    name: "vault-backend"
    kind: "ClusterSecretStore"

# QTodo application configuration
app:
  name: qtodo

# PostgreSQL database configuration
postgresql:
  name: qtodo-db

  # Database configuration
  auth:
    secretName: qtodo-db-secret
    database: tasks
    username: qtodo_user
    passwordVaultKey: secret/data/global/qtodo
